config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admins do
    resources :categories
    resources :users, only: [:index, :update]
    resources :blogs, only: [:index, :edit, :update]
    root 'blogs#index'
  end


  resources :categories, only: :show
  resources :blogs do
    resources :comments

    member do 
      post :collect
      post :uncollect
    end

  end
  
  #delete comment
  resources :comments, only: :destroy

  resources :users do
    resources :comments
    member do
      
    end
  end


  
  namespace :api, dedaults: {format: :json} do
    namespace :v1 do
      post "/login" => 'auth#login'
      post '/logout' => 'auth#logout'
    end
  end

  root 'blogs#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  attr :category_id

  belongs_to :user
  has_many :sorts, dependent: :destroy
  has_many  :categories, through: :sorts
  has_many :collect_blogs
  has_many :comments

  def has_category?(category_id)
    self.categories.include?(category_id)
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sorts
  has_many :blogs, through: :sorts
end

app/models/collect_blog.rb
class CollectBlog < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog, counter_cache: true
end

app/models/cotegory.rb
class Cotegory < ApplicationRecord
  has_many :blogs
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  has_many :firendships
  has_many :friends, through: :firendships
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/sort.rb
class Sort < ApplicationRecord
  belongs_to :category
  belongs_to :blog

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs
  has_many :comments
  has_many :collect_blogs
  has_many :collecting_blogs, through: :collect_blogs, source: :blog

  def admin?
    return self.role == "admin"
  end

end

app/controllers/admins/blogs_controller.rb
class Admins::BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

  def index
    @blogs = Blog.all
  end

  private

  def admin?
    current_user.role == "admin"
  end

  def authenticate_admin
    unless admin?
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
    @categories = Category.all
  end

  def create
    @blog = current_user.blogs.create(blog_params)
    params["blog"]["category_id"].each do |sort|
      @blog.sorts.create(:category_id => sort.to_i )
    end
    redirect_to root_path
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update

  end

  def collect
    blog = Blog.find(params[:id])
    @collect_blog = CollectBlog.new(user: current_user, blog: blog)
    @collect_blog.save
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :user_id, :photo, :content, :auth, :state)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @blogs = @category.blogs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)
    @comment.user = current_user
    @comment.save

    redirect_to blog_path(@blog)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to blog_path(@comment.blog)
  end
  
  private

  def comment_params
    params.require(:comment).permit(:commenter, :blog)
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
        
  end
  

end

app/helpers/admins/blogs_helper.rb
module Admins::BlogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/collect_blogs_helper.rb
module CollectBlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/blogs/index.html.erb
<h1>This is admins root</h1>
<% @blogs.each do |blog| %>
<ul>
  <%= render :partial => "shared/blog_list", :locals => {blog: blog }%>
</ul>
<% end %>

app/views/blogs/index.html.erb
<% if current_user%>
  <%= link_to "MY Profile", user_path(current_user)%>
<% end %>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Dojo Forum</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <ul class= "nav nav-pills">
      <li role= "presentation" class= "nav-item" ><%= link_to "All", root_path, class: "nav-link active"%></li>
      <% @categories.each do |category| %>
        <li role= "presentation" class= "nav-item" ><%= link_to category.title, category_path(category), class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
  <br>
  <div>
    <%= link_to "create", new_blog_path%>
  </div>
  <div class="row">
    <ul>
      <% @blogs.each do |blog| %>
        <%= render "shared/blog_list", blog: blog %>
      <% end %>
    </ul>
    
  </div>
</div>

app/views/blogs/new.html.erb
<%= form_for @blog do |f| %>

  <div class= "form-group">
    <%= f.text_field :title, class: "form-controller" ,placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.text_area :content, class: "form-controller", placeholder: "Content"  %>
  </div>

  <div class="form-group">
    <%= f.label :auth%>
    <div class="form-check form-check-inline">
      <%= f.radio_button :auth, 2 , class: "form-check-input"%>
      <label class="form-check-label" for="inlineRadio1">All</label>
    </div>

    <div class="form-check form-check-inline">
      <%= f.radio_button :auth, 1 , class: "form-check-input"%>
      <label class="form-check-label" for="inlineRadio1">Friend</label>
    </div>

    <div class="form-check form-check-inline">
      <%= f.radio_button :auth, 0 , class: "form-check-input"%>
      <label class="form-check-label" for="inlineRadio1">Self</label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <div class="form-check form-check-inline">
    <% Category.all.each do |category| %>
      <%= check_box_tag "blog[category_id][]", category.id, true, id: dom_id(category) , class: "form-check-input"  %> 
      <%= label_tag dom_id(category), category.title, class: "form-check-label" %> <br>
    <% end %>
    </div>
  </div>

  <div class="field">
    <%= f.label :state %>
    <span class="badge "> <%= @blog.state%> </span>
  </div>

  <div class="actions btn-inline">
      <% if @blog.state %>
        <%= f.submit 'Unpublish', class: 'btn btn-outline-secondary' %>
        <%= f.submit 'Update', class: 'btn btn-outline-primary' %>
      <% else%>
        <%= f.submit 'Draft', class: 'btn btn-secondary' %>
        <%= f.submit 'Publish', class: 'btn btn-primary' %>
      <% end %>
    </div>
<% end %>

app/views/blogs/show.html.erb
<h1> this is blog show page</h1>

<%= form_for [@blog, Comment.new] do |f| %>
  <%= f.text_field :commenter%>
  <%= f.submit "create"%>
<% end %>

<ul>
  <% @blog.comments.each do |comment|%>
    <%= render :partial => 'shared/comment_list', :locals => { comment: comment }%>
  <% end %>
</ul>