config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admins do
    resources :categories
    resources :users, only: [:index, :update]
    resources :blogs, only: [:index, :edit, :update]
    root 'blogs#index'
  end


  resources :categories, only: :show
  resources :blogs do
    resources :comments

    member do 
      post :collect
      post :uncollect
    end

  end
  
  #delete comment
  resources :comments, only: :destroy

  resources :users do
    resources :comments
    member do
      
    end
  end


  
  namespace :api, dedaults: {format: :json} do
    namespace :v1 do
      post "/login" => 'auth#login'
      post '/logout' => 'auth#logout'
    end
  end

  root 'blogs#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  attr :category_id

  belongs_to :user
  has_many :sorts, dependent: :destroy
  has_many  :categories, through: :sorts
  has_many :collect_blogs
  has_many :comments

  def has_category?(category_id)
    self.categories.include?(category_id)
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sorts
  has_many :blogs, through: :sorts
end

app/models/collect_blog.rb
class CollectBlog < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog, counter_cache: true
end

app/models/cotegory.rb
class Cotegory < ApplicationRecord
  has_many :blogs
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  has_many :firendships
  has_many :friends, through: :firendships
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/sort.rb
class Sort < ApplicationRecord
  belongs_to :category
  belongs_to :blog

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs
  has_many :comments
  has_many :collect_blogs
  has_many :collecting_blogs, through: :collect_blogs, source: :blog

  def admin?
    return self.role == "admin"
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
    @categories = Category.all
  end

  def create
    @blog = current_user.blogs.create(blog_params)
    params["blog"]["category_id"].each do |sort|
      @blog.sorts.create(:category_id => sort.to_i )
    end
    redirect_to root_path
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update

  end

  def collect
    blog = Blog.find(params[:id])
    @collect_blog = CollectBlog.new(user: current_user, blog: blog)
    @collect_blog.save
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :user_id, :photo, :content, :auth, :state)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)
    @comment.user = current_user
    @comment.save

    redirect_to blog_path(@blog)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to blog_path(@comment.blog)
  end
  
  private

  def comment_params
    params.require(:comment).permit(:commenter, :blog)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
        
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/collect_blogs_helper.rb
module CollectBlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DojoForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
      <%= link_to root_path do %>
        <%#= image_tag "wall.jpg", class: "rounded-circle avatar-navi" %>
      <% end %>
      <a class="navbar-brand" href="<%= root_path %>">Dojo Forum</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%# <%= link_to "Feed", feeds_posts_path, class: "nav-link"%> %>
          </li>
          <li class="nav-item">
            <%= link_to "All Post", root_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "New Post", new_blog_path, class: "nav-link"%>
          </li>
        </ul>
      </div>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
           <li><%= link_to '修改密碼', edit_user_registration_path, class: "nav-link" %></li>

            <% if current_user.admin? %>
              <li><%= link_to 'Admin', admins_users_path, class: "nav-link" %></li>
            <% end %>

            <li><%= link_to '登出', destroy_user_session_path, method: :delete, class: "nav-link" %></li>

            <%= link_to(user_path(current_user)) do %>
              <div class="avatar-navi">
                <%# <%= image_tag current_user.avatar.url, class: "img-fluid rounded" %> %>
              </div>
            <% end %>

            
          <% else %>

            <li><%= link_to '登入', new_user_session_path, class: "nav-link" %></li>

          <% end %>

        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/shared/_blog_list.html.erb
<li>
  <%= blog.title %>
  <%= link_to blog.title, blog_path(blog)%>
  <%= link_to "Collect", collect_blog_path(blog), method: :post%>
  <% if current_user.admin? %>
    <%= link_to "Delete", blog_path(blog), method: :delete %>
  <% end %>
</li>

app/views/shared/_comment_list.html.erb
<li>
  <%= comment.commenter %>
  <%= link_to "Delete", comment_path(comment), method: :delete %>
</li>